Remove unused dependencies for feed_cache/feed_remote
- don't need koin if we're using dagger
- feed_remote fails with "error: incompatible types: NonExistentClass cannot be converted to Annotation" when I remove koin, unless I add kotlin-android-ext
- no idea what's in there that makes it work